print("My Name is Banty Kumar")
print("My Age is 18")
print("My Crush is Rashmika ")
print("My Hobby is Enjoy THe Life")
print("My Work Breathing The Oxygen")
print("My Inspiration Is Keyur SIr")
print("My Favorite Color Is Not Available")
print("My Soap is Slow Beacsue i am Banty")
print("My Height is Very Lamba")
print("My SKin COlor is Goora")
print("My Hair IS Lamba")
print("My DReam is To Became A Pati")
print("My Favorite Movie is Demon SLyaer")